# Generated by Django 4.1.5 on 2024-06-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='projects/')),
                ('project_name', models.CharField(max_length=50)),
                ('project_link', models.CharField(max_length=150)),
                ('project_date', models.DateTimeField()),
            ],
        ),
    ]
