# Generated by Django 4.1.5 on 2024-06-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0002_myproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='education_imgs/')),
                ('edu_name', models.CharField(max_length=200)),
                ('edu_description', models.TextField()),
            ],
        ),
    ]
